# Generated by Django 3.0.8 on 2021-09-19 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateTimeField(help_text='Dia de disponibilidad del menu', verbose_name='Fecha de creacion')),
                ('menus_solicitados', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=False, help_text='La seleccion del menu solo estara disponible hasta las 11 de la mañana.', verbose_name='Menu activo')),
            ],
            options={
                'ordering': ['-fecha'],
                'get_latest_by': 'fecha',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=500, verbose_name='descripcion')),
                ('observaciones', models.CharField(blank=True, help_text='Permite al empleado personalizar y enviar sus preferencias', max_length=500, null=True, verbose_name='especificar personalizaciones')),
                ('postre', models.BooleanField(default=True, verbose_name='postre')),
                ('ensalada', models.BooleanField(default=True, verbose_name='ensalada')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
